# This is a basic workflow to help you get started with Actions
# GitHub action
# by Djamalov Jaloliddin 2022...
name: my-GitHub-action-test

on:
  push:
    branches: 
      - master

  
jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
    - name: Print message
      run: echo "Hello world from testing job"

  my_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print message
      run: echo "Hello world from deploy job"
